version: '3'

services:
  db:
    ports:
      - "5433:5432"
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#  webcachesim-server:
#    command: ./run.sh
#    build: .
#    volumes:
#      - .:/webcachesim_manager
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
