# Generated by Django 3.0.3 on 2020-02-22 03:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField(unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Running'), (-1, 'Failed'), (2, 'Done')], default=0)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('host', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('total_count', models.BigIntegerField(null=True)),
                ('current_count', models.BigIntegerField(null=True)),
                ('count_per_second', models.BigIntegerField(null=True)),
            ],
        ),
    ]
