# Generated by Django 3.0.3 on 2020-02-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200222_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=2000)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='executing_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.RemoteHost'),
        ),
    ]
