# Generated by Django 3.0.3 on 2020-02-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200222_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executing_host',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.RemoteHost'),
        ),
    ]
