# Generated by Django 3.0.3 on 2020-02-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200222_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='host',
        ),
    ]
